// Package caddy manages the Caddy reverse-proxy config for deployed services.
//
// Each service with at least one domain entry and an assigned host port gets a
// site block written to /etc/caddy/featherdeploy-services.caddy.  Caddy is then
// signalled to reload so the new config takes effect without downtime.
package caddy

import (
	"bytes"
	"context"
	"database/sql"
	"fmt"
	"io"
	"log/slog"
	"net/http"
	"os"
	"os/exec"
	"strings"
	"sync"
	"time"

	"github.com/ojhapranjal26/featherdeploy/backend/internal/coordination"
	"github.com/ojhapranjal26/featherdeploy/backend/internal/netdaemon"
)

var (
	EtcdClient *coordination.Client
	reloadMu   sync.Mutex
	executionMu sync.Mutex
	reloadTimer *time.Timer
)

func SetEtcdClient(c *coordination.Client) { EtcdClient = c }

const (
	servicesFile  = "/etc/caddy/featherdeploy-services.caddy"
	mainFile      = "/etc/caddy/Caddyfile"
	panelFile     = "/etc/caddy/featherdeploy-panel.caddy"
	importLine    = "import /etc/caddy/featherdeploy-services.caddy"
	panelImport   = "import /etc/caddy/featherdeploy-panel.caddy"
)

// WritePanelSnippet writes (or overwrites) a dedicated Caddy snippet for the
// panel reverse proxy that adds flush_interval -1 to ensure SSE log streams
// are not buffered by Caddy. This must be imported in the main Caddyfile.
// panelDomain is the domain Caddy already proxies to this backend
// (e.g. "panel.intelectio.art"). backendAddr is where this process listens
// (e.g. "127.0.0.1:8080").
func WritePanelSnippet(panelDomain, backendAddr string) {
	if panelDomain == "" || backendAddr == "" {
		return
	}
	snippet := fmt.Sprintf(`# Auto-generated by FeatherDeploy — do not edit manually
# This file ensures SSE endpoints (live logs) are not buffered by Caddy.
%s {
	reverse_proxy %s {
		flush_interval -1
		header_up Host {host}
		header_up X-Real-IP {remote_host}
	}
}
`, panelDomain, backendAddr)

	// Try direct write first (service runs as root or has /etc/caddy group-write)
	if err := os.WriteFile(panelFile, []byte(snippet), 0644); err != nil {
		// Fallback to sudo tee
		cmd := exec.Command("sudo", "-n", "tee", panelFile)
		cmd.Stdin = strings.NewReader(snippet)
		cmd.Stdout = io.Discard
		if err2 := cmd.Run(); err2 != nil {
			slog.Warn("caddy: could not write panel snippet", "err", err, "teeErr", err2)
			return
		}
	}
	slog.Info("caddy: panel snippet written", "path", panelFile, "domain", panelDomain)

	// Ensure the panel snippet is imported in the main Caddyfile
	data, err := os.ReadFile(mainFile)
	if err != nil {
		return
	}
	if !strings.Contains(string(data), "featherdeploy-panel.caddy") {
		// First remove the old site block for this domain if it exists,
		// then append the import so our snippet takes over
		appendLine := fmt.Sprintf("\nimport /etc/caddy/featherdeploy-panel.caddy\n")
		if err := os.WriteFile(mainFile, append(data, []byte(appendLine)...), 0644); err != nil {
			cmd := exec.Command("sudo", "-n", "tee", "-a", mainFile)
			cmd.Stdin = strings.NewReader(appendLine)
			cmd.Stdout = io.Discard
			_ = cmd.Run()
		}
		slog.Info("caddy: panel snippet import added to Caddyfile")
		reloadCaddy()
	}
}

// Reload regenerates the services Caddyfile from the DB and signals Caddy to
// reload. It uses a mutex to prevent concurrent writes and a 500ms debounce
// timer to collapse rapid sequential requests (e.g. from a bulk deploy).
func Reload(db *sql.DB) {
	reloadMu.Lock()
	defer reloadMu.Unlock()

	if reloadTimer != nil {
		reloadTimer.Stop()
	}

	reloadTimer = time.AfterFunc(1000*time.Millisecond, func() {
		performReload(db)
	})
}

func performReload(db *sql.DB) {
	executionMu.Lock()
	defer executionMu.Unlock()

	// Skip when Caddy is not installed (dev / CI)
	if !caddyInstalled() {
		return
	}

	content, err := buildConfig(db)
	if err != nil {
		slog.Warn("caddy: build config", "err", err)
		return
	}

	if content == "" {
		slog.Info("caddy: skipping reload, no active sites generated")
		return
	}

	slog.Info("caddy: generated config", "sites", strings.Count(content, "reverse_proxy"), "bytes", len(content))

	if err := writeServicesFile(content); err != nil {
		slog.Warn("caddy: write services file", "err", err)
		return
	}
	slog.Info("caddy: services file written", "path", servicesFile)

	ensureImport()
	reloadCaddy()
}

// caddyInstalled checks whether caddy is present on the system.
func caddyInstalled() bool {
	if _, err := exec.LookPath("caddy"); err == nil {
		return true
	}
	// exec.LookPath relies on the current PATH which may be restricted inside
	// a systemd service.  Check common install locations directly.
	for _, p := range []string{"/usr/bin/caddy", "/usr/local/bin/caddy"} {
		if _, err := os.Stat(p); err == nil {
			return true
		}
	}
	return false
}

// caddyBin returns the absolute path of the caddy binary.
func caddyBin() string {
	if p, err := exec.LookPath("caddy"); err == nil {
		return p
	}
	for _, p := range []string{"/usr/bin/caddy", "/usr/local/bin/caddy"} {
		if _, err := os.Stat(p); err == nil {
			return p
		}
	}
	return "caddy"
}

// buildConfig queries all (domain, tls, proxy_port) rows and returns a Caddyfile
// snippet with one site block per domain.
//
// Only domains that meet ALL of the following are included:
//   - DNS has been verified (d.verified = 1) — prevents broken TLS provisioning
//     for domains not yet pointing at this server.
//   - The backing service is actively running (s.status = 'running') — prevents
//     502 errors when a container is stopped, crashed, or not yet deployed.
//   - The service has a published host port (s.host_port > 0).
//
// Proxy target port selection (preferred → fallback):
//   1. s.cluster_port — the fdnet Go TCP proxy port (0.0.0.0:30000+, real kernel
//      socket).  Always reliable because fdnet's net.Listen() call creates an
//      actual kernel TCP socket that Caddy can connect to regardless of how the
//      container's slirp4netns port-forwarding is set up.
//   2. s.host_port — the slirp4netns userspace port-forward (127.0.0.1:10000+).
//      Used as a fallback for services deployed before the cluster_port column
//      was added (backward compatibility).  This can fail for services beyond
//      the first when the slirp4netns port-forwarding helper doesn't bind all
//      published ports reliably.
func buildConfig(db *sql.DB) (string, error) {
	rows, err := db.Query(`
		SELECT d.domain, d.tls,
		       COALESCE(s.cluster_port, s.host_port) AS proxy_port,
		       n.ip AS node_ip,
		       s.project_id, s.name AS svc_name,
		       COALESCE(s.node_id, 'main') AS node_id
		FROM   domains d
		JOIN   services s ON s.id = d.service_id
		LEFT JOIN nodes n ON n.node_id = s.node_id
		WHERE  s.host_port > 0
		  AND  s.status    = 'running'
		  AND  d.verified  = 1
		ORDER  BY d.domain
	`)
	if err != nil {
		return "", fmt.Errorf("query domains: %w", err)
	}
	defer rows.Close()

	var sb strings.Builder
	sb.WriteString("# Auto-generated by FeatherDeploy — do not edit manually\n")
	serverIP := os.Getenv("SERVER_IP")
	myHostname, _ := os.Hostname()

	for rows.Next() {
		var domain string
		var tlsInt, hostPort int
		var nodeIP sql.NullString
		var projectID int64
		var svcName, nodeIDStr string
		if rows.Scan(&domain, &tlsInt, &hostPort, &nodeIP, &projectID, &svcName, &nodeIDStr) != nil {
			continue
		}
		domain = strings.TrimSpace(strings.ToLower(domain))
		if domain == "" || hostPort <= 0 {
			continue
		}

		targetIP := "127.0.0.1"
		if nodeIP.Valid && nodeIP.String != "" {
			targetIP = nodeIP.String
		}

		isLocal := nodeIDStr == "main" || nodeIDStr == myHostname || (serverIP != "" && targetIP == serverIP)

		// If the service runs on the local brain node, force loopback routing to prevent external interface hairpin NAT drops.
		if isLocal {
			targetIP = "127.0.0.1"
		}

		// Try to resolve from Etcd for live endpoint metadata (highest priority)
		if EtcdClient != nil {
			// Use a 2-second timeout for discovery to prevent a hung etcd from
			// blocking the entire Caddy reload.
			ctx, cancel := context.WithTimeout(context.Background(), 2*time.Second)
			if ip, port, err := EtcdClient.DiscoverService(ctx, projectID, svcName); err == nil {
				cancel()
				// Basic validation: ensure we didn't get empty/zero data that would
				// result in a broken 'reverse_proxy :0' config.
				if ip != "" && port > 0 {
					targetIP = ip
					hostPort = port
					if isLocal || (serverIP != "" && targetIP == serverIP) {
						targetIP = "127.0.0.1"
					}
				}
			} else {
				cancel()
			}
		}

		// If the container runs on a remote worker node, ensure its traffic is tunneled securely over our loopback proxy
		if !isLocal && targetIP != "127.0.0.1" && netdaemon.GlobalTunnel != nil {
			localProxyPort := netdaemon.GlobalTunnel.EnsureServiceProxy(nodeIDStr, hostPort)
			if localProxyPort > 0 {
				targetIP = "127.0.0.1"
				hostPort = localProxyPort
			}
		}

		if tlsInt == 1 {
			// No scheme prefix → Caddy auto-provisions HTTPS via Let's Encrypt
			fmt.Fprintf(&sb, "\n%s {\n\tlog {\n\t\toutput stdout\n\t}\n\treverse_proxy %s:%d {\n\t\theader_up Host {host}\n\t\theader_up X-Real-IP {remote_host}\n\t}\n}\n", domain, targetIP, hostPort)
		} else {
			fmt.Fprintf(&sb, "\nhttp://%s {\n\tlog {\n\t\toutput stdout\n\t}\n\treverse_proxy %s:%d {\n\t\theader_up Host {host}\n\t\theader_up X-Real-IP {remote_host}\n\t}\n}\n", domain, targetIP, hostPort)
		}
	}
	return sb.String(), nil
}

// writeServicesFile writes content to servicesFile.  It tries, in order:
//  1. Atomic write via temp file + rename (works when /etc/caddy/ is group-writable
//     for the featherdeploy user, set by the installer via chgrp+chmod g+w)
//  2. Direct truncate + write (works when the file is owned by the service user)
//  3. sudo tee (guaranteed by the NOPASSWD sudoers rule written by writeSudoersFile)
func writeServicesFile(content string) error {
	// Attempt 1: temp file + atomic rename.
	// Requires write+execute on the /etc/caddy/ directory (set by installer).
	tmp := servicesFile + ".tmp"
	if err := os.WriteFile(tmp, []byte(content), 0644); err == nil {
		if err := os.Rename(tmp, servicesFile); err == nil {
			slog.Info("caddy: services file written (atomic rename)", "path", servicesFile)
			return nil
		}
		os.Remove(tmp) //nolint
	}

	// Attempt 2: direct write (works when the file is owned by the service user).
	if err := os.WriteFile(servicesFile, []byte(content), 0644); err == nil {
		slog.Info("caddy: services file written (direct write)", "path", servicesFile)
		return nil
	}

	// Attempt 3: sudo tee — requires the NOPASSWD rule written by writeSudoersFile().
	// featherdeploy ALL=(root) NOPASSWD: /usr/bin/tee /etc/caddy/featherdeploy-services.caddy
	slog.Info("caddy: falling back to sudo tee for services file")
	cmd := exec.Command("sudo", "-n", "tee", servicesFile)
	cmd.Stdin = strings.NewReader(content)
	var teeErr bytes.Buffer
	cmd.Stdout = io.Discard
	cmd.Stderr = &teeErr
	if err := cmd.Run(); err != nil {
		return fmt.Errorf("all write methods failed (sudo tee: %w — stderr: %s)", err, strings.TrimSpace(teeErr.String()))
	}
	slog.Info("caddy: services file written (sudo tee)", "path", servicesFile)
	return nil
}

// ensureImport appends the import directive to the main Caddyfile if it is not
// already present.  Tries a direct append first; falls back to sudo.
func ensureImport() {
	data, err := os.ReadFile(mainFile)
	if err != nil {
		return
	}
	if strings.Contains(string(data), "featherdeploy-services.caddy") {
		return
	}

	// Try direct append (works when running as root or when the file is group-writable)
	f, err := os.OpenFile(mainFile, os.O_APPEND|os.O_WRONLY, 0644)
	if err == nil {
		fmt.Fprintf(f, "\n%s\n", importLine)
		f.Close()
		slog.Info("caddy: added import to Caddyfile")
		return
	}

	// Fallback: use sudo (requires NOPASSWD sudoers rule)
	snippet := fmt.Sprintf("\n%s\n", importLine)
	cmd := exec.Command("sudo", "-n", "tee", "-a", mainFile)
	cmd.Stdin = strings.NewReader(snippet)
	cmd.Stdout = io.Discard
	if err := cmd.Run(); err != nil {
		slog.Warn("caddy: could not add import to Caddyfile", "err", err)
	} else {
		slog.Info("caddy: added import to Caddyfile via sudo")
	}
}

// reloadCaddy signals Caddy to reload its config without downtime.
// It tries three methods in order of reliability, retrying each up to 3 times
// with a 2-second gap so transient systemd / socket races don't cause failures:
//  1. sudo systemctl reload caddy — sends SIGUSR1; Caddy re-reads the
//     Caddyfile from disk and resolves all import directives itself.
//  2. caddy reload CLI — reads the config file and POSTs it via the admin API.
//  3. Caddy admin API via HTTP — we manually inline imported files and POST
//     the merged config.  Fallback because import resolution
//     via the /adapt endpoint can be unreliable.
func reloadCaddy() {
	const maxTries = 3

	// Method 1: sudo systemctl reload caddy (sends SIGUSR1 → graceful reload).
	// Most reliable: Caddy reads config from disk and resolves all imports.
	for i := 0; i < maxTries; i++ {
		if out, err := exec.Command("sudo", "-n", "systemctl", "reload", "caddy").CombinedOutput(); err == nil {
			slog.Info("caddy: reloaded via systemctl")
			return
		} else {
			slog.Warn("caddy: systemctl reload attempt failed", "attempt", i+1, "err", err, "out", strings.TrimSpace(string(out)))
		}
		time.Sleep(2 * time.Second)
	}

	// Method 2: caddy reload CLI reads the config from disk and POSTs to admin
	// API.  Import directives are resolved by the caddy binary.
	bin := caddyBin()
	for i := 0; i < maxTries; i++ {
		if out, err := exec.Command(bin, "reload", "--config", mainFile, "--adapter", "caddyfile").CombinedOutput(); err == nil {
			slog.Info("caddy: reloaded via CLI")
			return
		} else {
			slog.Warn("caddy: CLI reload attempt failed", "attempt", i+1, "err", err, "bin", bin, "out", strings.TrimSpace(string(out)))
		}
		time.Sleep(2 * time.Second)
	}

	// Method 3: POST the Caddyfile to the admin API with inlined imports.
	for i := 0; i < maxTries; i++ {
		if reloadViaAPI() {
			slog.Info("caddy: reloaded via admin API (HTTP)")
			return
		}
		if i < maxTries-1 {
			time.Sleep(2 * time.Second)
		}
	}

	slog.Error("caddy: all reload methods failed — domains may not resolve until next reload")
}

// reloadViaAPI reads the main Caddyfile, manually inlines the services import
// file, adapts the merged config to JSON via the admin API, then loads it.
func reloadViaAPI() bool {
	c := &http.Client{Timeout: 5 * time.Second}

	// Read the full Caddyfile (which contains the import directive)
	data, err := os.ReadFile(mainFile)
	if err != nil {
		slog.Warn("caddy: api reload: cannot read Caddyfile", "err", err)
		return false
	}

	// Manually resolve the services import so the /adapt API doesn't need to
	// do filesystem-based import resolution (which can be unreliable).
	content := string(data)
	if svcData, readErr := os.ReadFile(servicesFile); readErr == nil {
		content = strings.Replace(content, importLine, string(svcData), 1)
		// Also handle the import with a "import" prefix in case the Caddyfile
		// uses the raw line form
		content = strings.Replace(content, "import "+servicesFile, string(svcData), 1)
	}

	// Step 1: Adapt the Caddyfile to JSON via POST /adapt
	adaptReq, _ := http.NewRequest("POST", "http://localhost:2019/adapt", strings.NewReader(content))
	adaptReq.Header.Set("Content-Type", "text/caddyfile")
	adaptResp, err := c.Do(adaptReq)
	if err != nil {
		slog.Warn("caddy: api reload: adapt request failed", "err", err)
		return false
	}
	defer adaptResp.Body.Close()
	jsonConfig, _ := io.ReadAll(adaptResp.Body)
	if adaptResp.StatusCode != 200 {
		slog.Warn("caddy: api reload: adapt returned error", "status", adaptResp.StatusCode, "body", string(jsonConfig))
		return false
	}

	// Step 2: Load the JSON config via POST /load
	loadReq, _ := http.NewRequest("POST", "http://localhost:2019/load", bytes.NewReader(jsonConfig))
	loadReq.Header.Set("Content-Type", "application/json")
	loadResp, err := c.Do(loadReq)
	if err != nil {
		slog.Warn("caddy: api reload: load request failed", "err", err)
		return false
	}
	defer loadResp.Body.Close()
	if loadResp.StatusCode != 200 {
		body, _ := io.ReadAll(loadResp.Body)
		slog.Warn("caddy: api reload: load returned error", "status", loadResp.StatusCode, "body", string(body))
		return false
	}
	return true
}
