// Package caddy manages the Caddy reverse-proxy config for deployed services.
//
// Each service with at least one domain entry and an assigned host port gets a
// site block written to /etc/caddy/featherdeploy-services.caddy.  Caddy is then
// signalled to reload so the new config takes effect without downtime.
package caddy

import (
	"database/sql"
	"fmt"
	"log/slog"
	"os"
	"os/exec"
	"strings"
)

const (
	servicesFile = "/etc/caddy/featherdeploy-services.caddy"
	mainFile     = "/etc/caddy/Caddyfile"
	importLine   = "import /etc/caddy/featherdeploy-services.caddy"
)

// Reload regenerates the services Caddyfile from the DB and signals Caddy to
// reload.  It is intentionally fire-and-forget friendly: all errors are logged
// but never returned so callers don't need to handle them.
func Reload(db *sql.DB) {
	if _, err := exec.LookPath("caddy"); err != nil {
		return // dev / CI environment — Caddy not installed
	}

	content, err := buildConfig(db)
	if err != nil {
		slog.Warn("caddy: build config", "err", err)
		return
	}

	if err := writeServicesFile(content); err != nil {
		slog.Warn("caddy: write services file", "err", err)
		return
	}

	ensureImport()
	reloadCaddy()
}

// buildConfig queries all (domain, tls, host_port) rows and returns a Caddyfile
// snippet with one site block per domain.
func buildConfig(db *sql.DB) (string, error) {
	rows, err := db.Query(`
		SELECT d.domain, d.tls, s.host_port
		FROM   domains d
		JOIN   services s ON s.id = d.service_id
		WHERE  s.host_port > 0
		ORDER  BY d.domain
	`)
	if err != nil {
		return "", fmt.Errorf("query domains: %w", err)
	}
	defer rows.Close()

	var sb strings.Builder
	sb.WriteString("# Auto-generated by FeatherDeploy — do not edit manually\n")

	for rows.Next() {
		var domain string
		var tlsInt, hostPort int
		if rows.Scan(&domain, &tlsInt, &hostPort) != nil {
			continue
		}
		domain = strings.TrimSpace(strings.ToLower(domain))
		if domain == "" || hostPort <= 0 {
			continue
		}
		if tlsInt == 1 {
			// No scheme prefix → Caddy auto-provisions HTTPS via Let's Encrypt
			fmt.Fprintf(&sb, "\n%s {\n\treverse_proxy 127.0.0.1:%d\n}\n", domain, hostPort)
		} else {
			fmt.Fprintf(&sb, "\nhttp://%s {\n\treverse_proxy 127.0.0.1:%d\n}\n", domain, hostPort)
		}
	}
	return sb.String(), nil
}

// writeServicesFile writes content to servicesFile atomically via a temp file.
// Falls back to direct write if the rename fails (cross-device edge case).
func writeServicesFile(content string) error {
	tmp := servicesFile + ".tmp"
	if err := os.WriteFile(tmp, []byte(content), 0644); err != nil {
		// /etc/caddy might not be writable by the service user on first run;
		// the build.sh step creates the file with the right ownership.
		return os.WriteFile(servicesFile, []byte(content), 0644)
	}
	if err := os.Rename(tmp, servicesFile); err != nil {
		os.Remove(tmp) //nolint
		return os.WriteFile(servicesFile, []byte(content), 0644)
	}
	return nil
}

// ensureImport appends the import directive to the main Caddyfile if it is not
// already present.  Tries a direct append first; falls back to sudo.
func ensureImport() {
	data, err := os.ReadFile(mainFile)
	if err != nil {
		return
	}
	if strings.Contains(string(data), "featherdeploy-services.caddy") {
		return
	}

	// Try direct append (works when running as root or when the file is group-writable)
	f, err := os.OpenFile(mainFile, os.O_APPEND|os.O_WRONLY, 0644)
	if err == nil {
		fmt.Fprintf(f, "\n%s\n", importLine)
		f.Close()
		slog.Info("caddy: added import to Caddyfile")
		return
	}

	// Fallback: use sudo (requires NOPASSWD sudoers rule)
	snippet := fmt.Sprintf("\n%s\n", importLine)
	cmd := exec.Command("sudo", "-n", "tee", "-a", mainFile)
	cmd.Stdin = strings.NewReader(snippet)
	if err := cmd.Run(); err != nil {
		slog.Warn("caddy: could not add import to Caddyfile", "err", err)
	} else {
		slog.Info("caddy: added import to Caddyfile via sudo")
	}
}

// reloadCaddy signals Caddy to reload its config without downtime.
// First tries the Caddy admin API (no root needed), then falls back to
// systemctl reload via sudo.
func reloadCaddy() {
	// caddy reload --config <file> talks to the admin API on localhost:2019
	err := exec.Command("caddy", "reload", "--config", mainFile, "--adapter", "caddyfile").Run()
	if err == nil {
		slog.Info("caddy: reloaded via admin API")
		return
	}
	// Fallback: systemctl reload caddy (requires NOPASSWD sudoers rule)
	if out, err := exec.Command("sudo", "-n", "systemctl", "reload", "caddy").CombinedOutput(); err != nil {
		slog.Warn("caddy: reload failed", "err", err, "out", strings.TrimSpace(string(out)))
	} else {
		slog.Info("caddy: reloaded via systemctl")
	}
}
